name: Deploy

on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: self-hosted-pi

    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          clean: false

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps
        run: npm i

      - name: build the mother fucking thing
        run: npm run build

      - name: stupid puppeteer
        run: node node_modules/puppeteer/install.js

      - name: Deploy production
        run: pm2 restart prod
